##########################################################################
# Standard Properties
org.gradle.jvmargs = -Xmx2G
org.gradle.warning.mode = all
# This currently has to be set to false because the "Minecraft Client" and "Minecraft Server" configurations generated
# by IntelliJ aren't currently compatible with the configuration cache. If you use the runClient and runServer Gradle
# tasks instead, then this can (and should) be set to true.
org.gradle.configuration-cache = false
##########################################################################
# Standard BTA Dependencies
# Check this on https://downloads.betterthanadventure.net/bta-client/
bta_version = 7.3_04
# Options are release, prerelease, nightly, and misc.
bta_channel = release
# Check this on https://maven.thesignalumproject.net/#/infrastructure/net/fabricmc/fabric-loader/
loader_version = 0.17.3-bta.8
# Check this on https://maven.thesignalumproject.net/#/infrastructure/fabric-loom/fabric-loom.gradle.plugin/
loom_version = 1.13.0-bta
# The Java version the JDK will be for compiling and running code.
java_version = 8
# The Java version the JDK will be for running Gradle.
gradle_java_version = 21
##########################################################################
# Mod Properties
mod_version = 1.0.0
mod_group = turniplabs
mod_name = examplemod
##########################################################################
# Mod Dependencies
# Check this on https://github.com/Turnip-Labs/ModMenu/releases/latest/
mod_menu_version = 3.0.0
# Check this on https://github.com/Turnip-Labs/bta-halplibe/releases/latest/
halplibe_version = 5.3.1
# Check this on https://github.com/Better-than-Adventure/legacy-lwjgl3/releases/latest/
legacy_lwjgl_version = 1.0.6
##########################################################################
# 3rd Party Dependencies
# Check this on https://central.sonatype.com/artifact/org.slf4j/slf4j-api/
slf4j_api_version = 2.0.17
# Check this on https://central.sonatype.com/artifact/org.apache.logging.log4j/log4j-api/
log4j_version = 2.20.0
# Check this on https://central.sonatype.com/artifact/com.google.guava/guava/
guava_version = 33.5.0-jre
# Check this on https://central.sonatype.com/artifact/com.google.code.gson/gson/
gson_version = 2.13.2
# Check this on https://central.sonatype.com/artifact/org.apache.commons/commons-lang3/
commons_lang3_version = 3.20.0
# This should match the version used by the current BTA release.
lwjgl_version = 3.3.3
##########################################################################
# Plugin Dependency
# Check this on https://plugins.gradle.org/plugin/org.gradle.toolchains.foojay-resolver-convention/
foojay_resolver_version = 1.0.0
##########################################################################
